require(foreign)
require(data.table)
require(plyr)
require(maggritr)
require(reshape2)
require(broom)
require(data.table)
require(reshape2)
require(rgl)
require(stringr)
require(gnm)
require(dplyr)
require(ggplot2)
require(RColorBrewer)
require(gridExtra)
require(scales)
require(foreign)
require(lubridate)
require(gam)
require(reshape)
require(ChainLadder)

for_glm = cum2incr(RAA) %>% melt %>% data.table()
fit = glm(log(value)~as.factor(origin)+as.factor(dev),data=for_glm)
for_glm$loglin = exp(predict(fit,newdata=for_glm))